---
title: "Class 7 functions and packages"
author: "Yvette Tan"
date: "1/29/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Functions revisit
```{r}
source("http://tinyurl.com/rescale-R")
```

Lets try the rescale() function out
```{r}
rescale( c(1, 5, 10))
```
Let's try **rescale2()** with the **stop()** function catch for non-numeric input

**which()** : which element is true using 
```{r}
x <- c(3, 7, NA, 4, 8, NA)
which(is.na(x))
```

```{r}
#Let's define an example x and y
x <- c(1,2, NA, 3, NA)
y <- c(NA, 3, NA, 3, 4)

```
 
```{r}
is.na(x)
sum(is.na(x))

```
 
```{r}
is.na(x)
is.na(y)
is.na(x) & is.na(y)

#putting together!
sum(is.na(x) & is.na(y))
```
 
```{r}
x <- c(NA, NA, NA)
y1 <- c(1, NA, NA)
y2 <- c(1, NA, NA, NA)
y3 <- c(1, NA, NA, NA, NA)
y4 <- c(1, 1, NA)
both_na(x, y1)
both_na(x, y2)
both_na(x, y3)
both_na(y1, y3)
both_na(y4, y3)
#when length isn't equal, the shorter will rerun the vector from left to right until it matches the length of the longer vector
```

```{r}
both_na3(x, y1)
```







